# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3, 4, 5])


# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])


# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]]])


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)


((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [6]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)


((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2)
df


0  1  2
0  1  2  3
1  4  5  6

In [8]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros


array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100, 3)


In [12]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0, 10, size=(7, 2))
random_array


array([[6, 7],
       [6, 6],
       [5, 2],
       [4, 4],
       [0, 2],
       [3, 1],
       [5, 4]])

In [13]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_2 = np.random.random((3, 5))
random_array_2


array([[0.60930509, 0.71613146, 0.16488895, 0.4746571 , 0.99243381],
       [0.19912377, 0.35698223, 0.4287545 , 0.03077418, 0.05106817],
       [0.45872458, 0.62565939, 0.62797405, 0.90135912, 0.81679422]])

In [15]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_3 = np.random.randint(0, 10, size=(4, 6))
random_array_3


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [17]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array_4 = np.random.randint(1, 10, size=(3, 7))


# Find the unique numbers in the array you just created
print(random_array_4)
np.unique(random_array_4)


[[7 8 3 1 4 2 8]
 [4 2 6 6 4 6 2]
 [2 4 8 7 9 8 5]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Find the 0'th index of the latest array you created
random_array_4[0]


array([7, 8, 3, 1, 4, 2, 8])

In [19]:
# Get the first 2 rows of latest array you created
random_array_4[:2]


array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2]])

In [20]:
# Get the first 2 values of the first 2 rows of the latest array
random_array_4[:2, :2]


array([[7, 8],
       [4, 2]])

In [24]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array_5 = np.random.randint(0, 10, size=(3, 5))
ones = np.ones((3, 5))
print(random_array_5)
print(ones)


[[0 7 2 2 0]
 [4 9 6 9 8]
 [6 8 7 1 0]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
# Add the two arrays together
added_arr = random_array_5 + ones
added_arr

array([[ 1.,  8.,  3.,  3.,  1.],
       [ 5., 10.,  7., 10.,  9.],
       [ 7.,  9.,  8.,  2.,  1.]])

In [26]:
# Create another array of ones of shape (5, 3)
ones_2 = np.ones((5, 3))

In [27]:
# Try add the array of ones and the other most recent array together
add_try = ones_2 + random_array_5


ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is? ANSWER: different shapes

How would you fix it?
ANSWER: reshape

In [28]:
# Create another array of ones of shape (3, 5)
ones_3 = np.ones((3, 5))



In [30]:
# Subtract the new array of ones from the other most recent array
subtracted = random_array_5 - ones_3
subtracted


array([[-1.,  6.,  1.,  1., -1.],
       [ 3.,  8.,  5.,  8.,  7.],
       [ 5.,  7.,  6.,  0., -1.]])

In [31]:
# Multiply the ones array with the latest array
multiplied = random_array_5 * ones_3
multiplied

array([[0., 7., 2., 2., 0.],
       [4., 9., 6., 9., 8.],
       [6., 8., 7., 1., 0.]])

In [32]:
# Take the latest array to the power of 2 using '**'
power = random_array_5 ** 2
power


array([[ 0, 49,  4,  4,  0],
       [16, 81, 36, 81, 64],
       [36, 64, 49,  1,  0]])

In [33]:
# Do the same thing with np.square()
np.square(random_array_5)


array([[ 0, 49,  4,  4,  0],
       [16, 81, 36, 81, 64],
       [36, 64, 49,  1,  0]])

In [34]:
# Find the mean of the latest array using np.mean()
np.mean(random_array_5)


4.6

In [35]:
# Find the maximum of the latest array using np.max()
np.max(random_array_5)


9

In [36]:
# Find the minimum of the latest array using np.min()
np.min(random_array_5)


0

In [37]:
# Find the standard deviation of the latest array
np.std(random_array_5)


3.3426536364591137

In [39]:
# Find the variance of the latest array
np.var(random_array_5)

11.173333333333336

In [40]:
# Reshape the latest array to (3, 5, 1)
random_array_5.reshape(3, 5, 1)


array([[[0],
        [7],
        [2],
        [2],
        [0]],

       [[4],
        [9],
        [6],
        [9],
        [8]],

       [[6],
        [8],
        [7],
        [1],
        [0]]])

In [41]:
# Transpose the latest array
random_array_5.T


array([[0, 4, 6],
       [7, 9, 8],
       [2, 6, 7],
       [2, 9, 1],
       [0, 8, 0]])

What does the transpose do?

In [42]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_array_6 = np.random.randint(0, 10, size=(3, 3))
random_array_7 = np.random.randint(0, 10, size=(3, 2))
print('3*3 Array: ',random_array_6)
print('3*2 Array: ',random_array_7)


3*3 Array:  [[6 6 7]
 [4 2 7]
 [5 2 0]]
3*2 Array:  [[2 4]
 [2 0]
 [4 9]]


In [43]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array_6, random_array_7)


array([[52, 87],
       [40, 79],
       [14, 20]])

In [44]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_array_8 = np.random.randint(0, 10, size=(4, 3))
random_array_9 = np.random.randint(0, 10, size=(4, 3))
print('First Array: ',random_array_8)
print('Second Array: ',random_array_9)


First Array:  [[6 6 8]
 [9 9 2]
 [6 0 3]
 [3 4 6]]
Second Array:  [[6 3 6]
 [2 5 1]
 [9 8 4]
 [5 3 9]]


In [45]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array_8, random_array_9)
#  the shape of the arrays are not compatible for dot product
# so we need to transpose one of the arrays


ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [46]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(random_array_8, random_array_9.T)



array([[102,  50, 134, 120],
       [ 93,  65, 161,  90],
       [ 54,  15,  66,  57],
       [ 66,  32,  83,  81]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [47]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
random_array_10 = np.random.randint(0, 10, size=(4, 3))
random_array_11 = np.random.randint(0, 10, size=(4, 3))
print('First Array: ',random_array_10)
print('Second Array: ',random_array_11)


First Array:  [[6 8 6]
 [0 0 8]
 [8 3 8]
 [2 6 5]]
Second Array:  [[7 8 4]
 [0 2 9]
 [7 5 7]
 [8 3 0]]


In [48]:
# Compare the two arrays with '>'
random_array_10 > random_array_11


array([[False, False,  True],
       [False, False, False],
       [ True, False,  True],
       [False,  True,  True]])

What happens when you compare the arrays with `>`?

In [49]:
# Compare the two arrays with '>='
random_array_10 >= random_array_11


array([[False,  True,  True],
       [ True, False, False],
       [ True, False,  True],
       [False,  True,  True]])

In [53]:
# Find which elements of the first array are greater than 7
print(random_array_10 > 7)
random_array_10[random_array_10 > 7]


[[False  True False]
 [False False  True]
 [ True False  True]
 [False False False]]


array([8, 8, 8, 8])

In [54]:
# Which parts of each array are equal? (try using '==')
random_array_10 == random_array_11



array([[False,  True, False],
       [ True, False, False],
       [False, False, False],
       [False, False, False]])

In [60]:
random_array_10

array([[6, 8, 6],
       [0, 0, 8],
       [8, 3, 8],
       [2, 6, 5]])

In [62]:
# Sort one of the arrays you just created in ascending order

#sort elements of array along an axis
print(np.sort(random_array_10))


[[6 6 8]
 [0 0 8]
 [3 8 8]
 [2 5 6]]


To sort elementwise

In [75]:
sorted_by_val = np.sort(random_array_10.flatten()).reshape(random_array_10.shape)
sorted_by_val

array([[0, 0, 2],
       [3, 5, 6],
       [6, 6, 8],
       [8, 8, 8]])

In [77]:
# Sort the indexes of one of the arrays you just created
np.argsort(random_array_10) # row wise


array([[0, 2, 1],
       [0, 1, 2],
       [1, 0, 2],
       [0, 2, 1]])

In [112]:
# universal sorting indexing
# Get the sorted indices of the flattened array
sorted_indices_flat = np.argsort(random_array_10.flatten())

# Reshape the sorted indices back to the original shape
sorted_indices_2d = np.unravel_index(sorted_indices_flat, random_array_10.shape)

# Reshape the 2D indices back to the original shape
sorted_indices_array = np.vstack(sorted_indices_2d).T

print(sorted_indices_array) 

[[1 0]
 [1 1]
 [3 0]
 [2 1]
 [3 2]
 [3 1]
 [0 2]
 [0 0]
 [2 0]
 [1 2]
 [0 1]
 [2 2]]


In [108]:
# Find the index with the maximum value in one of the arrays you've created
max_index = np.argmax(random_array_10)

# Convert the flat index to 2D indices
max_index_2d = np.unravel_index(max_index, random_array_10.shape)

print(max_index_2d)
print(random_array_10[max_index_2d])

(0, 1)
8


In [109]:
# Find the index with the minimum value in one of the arrays you've created
min_index = np.argmin(random_array_10)

# Convert the flat index to 2D indices
min_index_2d = np.unravel_index(min_index, random_array_10.shape)

print(min_index_2d)
print(random_array_10[min_index_2d])

(1, 0)
0


In [111]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
max_index_1d = np.argmax(random_array_10, axis=1)
print(max_index_1d)


[1 2 0 1]


In [114]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
min_index_1d = np.argmin(random_array_10, axis=0)
print(min_index_1d)



[1 1 3]


In [120]:
# Create an array of normally distributed random numbers
mean_value = 0
std_dev = 1
array_size = (8, )  # Example size, adjust as needed

# Generate the array of normally distributed random numbers
random_array_normal = np.random.normal(mean_value, std_dev, array_size)
print(random_array_normal)

[ 0.71812828 -0.95147175 -0.5361601   1.09652886  0.42801284 -2.46969887
  0.48197914  0.92645636]


In [121]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)


array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.